# Generated by Django 4.1 on 2022-10-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_date_auction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='Description',
            field=models.TextField(max_length=100),
        ),
    ]
