# Generated by Django 4.1 on 2022-10-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='Description1',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='Description',
            field=models.CharField(max_length=64),
        ),
    ]
