# Generated by Django 4.1 on 2022-10-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_description1_alter_auction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='Description1',
        ),
        migrations.AlterField(
            model_name='auction',
            name='Description',
            field=models.TextField(max_length=100),
        ),
    ]
