# Generated by Django 4.1 on 2022-10-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auction_description1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Article', models.CharField(max_length=64)),
                ('Price', models.IntegerField()),
                ('Description', models.TextField(max_length=500)),
                ('Image', models.ImageField(null=b'I01\n', upload_to='media')),
            ],
        ),
        migrations.AlterField(
            model_name='auction',
            name='Description',
            field=models.TextField(max_length=500),
        ),
    ]
