# Generated by Django 4.1 on 2023-01-08 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_watchlist_owner_alter_auction_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='Owner',
        ),
        migrations.AlterField(
            model_name='auction',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
