# Generated by Django 4.1 on 2023-01-08 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_auction_owner_remove_watchlist_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.AddField(
            model_name='auction',
            name='Watchlist',
            field=models.ManyToManyField(blank=b'I01\n', null=b'I01\n', related_name='watchlist', to=settings.AUTH_USER_MODEL),
            preserve_default=b'I01\n',
        ),
    ]
